name: Check HTML

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_html:
    name: Lint HTML code
    runs-on: ubuntu-latest
    steps:
      - name: Download output artifact
        uses: actions/download-artifact@v7
        with:
          name: website_build_output
          path: output
      - name: Create empty package lock
        run: touch package-lock.json
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install html-validate
        run: |
          npm install -g html-validate
      - name: Run html-validate
        run: |
          for file in output/*.html; do
            html-validate  \
              --preset recommended \
              --rule wcag/h30:off \
              "output/${file}.html" || {
              echo "ERROR: HTML validation failed on ${file}"
              cat "${file}"
              exit 1
            }
          done
